Repository NeuroLang/NeuroLang, pull requests merged in 2021-07, with the labels that each got.

#626 Add documentation for exceptions in Neurolang
  neurolang/datalog/aggregation.py
  neurolang/datalog/basic_representation.py
  neurolang/datalog/negation.py
  neurolang/exceptions.py
Labels: doc

#638 Add try/finally in sure_is_not_pattern context
  neurolang/expressions.py
Labels: bug

#644 Fix bug on provenance RA when one of the sets is empty
  neurolang/probabilistic/probabilistic_ra_utils.py
  neurolang/probabilistic/probabilistic_semiring_solver.py
  neurolang/probabilistic/tests/test_probabilistic_solvers.py
  neurolang/probabilistic/weighted_model_counting.py
Labels: bug

#643 Added optimizations for trivial projections
  neurolang/relational_algebra.py
  neurolang/tests/test_relational_algebra.py
Labels: enhancement
