Repository NeuroLang/NeuroLang, pull requests merged in 2021-01, with the labels that each got.

#588 Minor bug fixes and documentation for relational algebra sets
  neurolang/utils/relational_algebra_set/abstract.py
  neurolang/utils/relational_algebra_set/pandas.py
  neurolang/utils/tests/test_relational_algebra_set.py
Labels: bug, doc

#593 Prevent some post-probabilistic rule to be considered as probabilistic
  neurolang/probabilistic/stratification.py
  neurolang/probabilistic/tests/test_stratification.py
Labels: bug

#585 Spatial prior through query-based probabilistic facts
  examples/plot_cbma_spatial_prior.py
  neurolang/datalog/expression_processing.py
  neurolang/datalog/tests/test_cq_disj_to_named_ra.py
  neurolang/datalog/wrapped_collections.py
  neurolang/frontend/datalog/sugar/__init__.py
  neurolang/frontend/datalog/sugar/spatial.py
  neurolang/frontend/datalog/sugar/tests/__init__.py
  neurolang/frontend/datalog/sugar/tests/test_intermediate_sugar.py
  neurolang/frontend/datalog/sugar/tests/test_spatial.py
  neurolang/frontend/deterministic_frontend.py
  neurolang/frontend/probabilistic_frontend.py
  neurolang/frontend/query_resolution.py
  neurolang/frontend/tests/test_probabilistic_frontend.py
  neurolang/probabilistic/expression_processing.py
  neurolang/probabilistic/query_resolution.py
  neurolang/probabilistic/stratification.py
  neurolang/probabilistic/tests/test_query_based_pfacts.py
  neurolang/relational_algebra.py
  neurolang/utils/relational_algebra_set/pandas.py
Labels: example
